defmodule WallopCore.Repo.Migrations.OpenDraws do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:draws) do
      modify(:entry_canonical, :text, null: true)
      modify(:entry_hash, :text, null: true)
      modify(:entries, {:array, :map}, null: true, default: [])
      modify(:status, :text, default: "open")
      add(:stage_timestamps, :map, default: %{})
    end
  end

  def down do
    alter table(:draws) do
      remove(:stage_timestamps)
      modify(:status, :text, default: "locked")
      modify(:entries, {:array, :map}, null: false, default: nil)
      modify(:entry_hash, :text, null: false)
      modify(:entry_canonical, :text, null: false)
    end
  end
end
