defmodule WallopCore.Repo.Migrations.AddNameToDraws do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:draws) do
      add(:name, :text)
    end
  end

  def down do
    alter table(:draws) do
      remove(:name)
    end
  end
end
