defmodule WallopCore.Repo.Migrations.CreateDraws do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:draws, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false, default: "locked")
      add(:entries, {:array, :map}, null: false)
      add(:entry_hash, :text, null: false)
      add(:entry_canonical, :text, null: false)
      add(:winner_count, :bigint, null: false)
      add(:seed, :text)
      add(:seed_source, :text)
      add(:seed_json, :text)
      add(:results, {:array, :map})
      add(:metadata, :map)
      add(:executed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :api_key_id,
        references(:api_keys,
          column: :id,
          name: "draws_api_key_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:draws, "draws_api_key_id_fkey"))

    drop(table(:draws))
  end
end
