defmodule WallopCore.Repo.Migrations.CreateApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:key_hash, :text, null: false)
      add(:key_prefix, :text, null: false)
      add(:active, :boolean, null: false, default: true)
      add(:deactivated_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:api_keys, [:key_prefix], name: "api_keys_unique_prefix_index"))
  end

  def down do
    drop_if_exists(unique_index(:api_keys, [:key_prefix], name: "api_keys_unique_prefix_index"))

    drop(table(:api_keys))
  end
end
