defmodule WallopCore.Repo.Migrations.AddEntropyFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:draws) do
      add(:drand_chain, :text)
      add(:drand_round, :bigint)
      add(:drand_randomness, :text)
      add(:drand_signature, :text)
      add(:drand_response, :text)
      add(:weather_station, :text)
      add(:weather_time, :utc_datetime_usec)
      add(:weather_value, :text)
      add(:weather_raw, :text)
      add(:callback_url, :text)
      add(:failed_at, :utc_datetime_usec)
      add(:failure_reason, :text)
    end

    alter table(:api_keys) do
      add(:webhook_secret, :text)
    end
  end

  def down do
    alter table(:api_keys) do
      remove(:webhook_secret)
    end

    alter table(:draws) do
      remove(:failure_reason)
      remove(:failed_at)
      remove(:callback_url)
      remove(:weather_raw)
      remove(:weather_value)
      remove(:weather_time)
      remove(:weather_station)
      remove(:drand_response)
      remove(:drand_signature)
      remove(:drand_randomness)
      remove(:drand_round)
      remove(:drand_chain)
    end
  end
end
