defmodule WallopCore.Repo.Migrations.AddWeatherObservationTime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:draws) do
      add(:weather_observation_time, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:draws) do
      remove(:weather_observation_time)
    end
  end
end
